language: python
python:
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.5-dev'
install: 
 - "pip install -r requirement.txt"
 - "pip install flake8"

before_script:
 - "flake8 ."

script: coverage

notifications:
  email: false

branches:
  only:
    - master
