language: python
python:
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.5-dev'
install: 
 - "pip install -r requirement.txt"
 - "pip install flake8"
 - "pip install codecov"

after_success:
 - codecov

before_script:
 - "flake8 ."

script:
 - "python setup.py install"

after_success:
 - codecov

notifications:
  email: false

branches:
  only:
    - master
