language: python
python:
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.5-dev'
  - 'nightly'
install: "pip install -r requirement.txt"
script: coverage

notifications:
  email: false

branches:
  only:
    - master
