#!/usr/bin/python3
from pythonCah.bot import CahBot
from pythonCah.config import loadConfig
from pythonCah.security import authentication_from_config
from pythonCah.dispatch import InpersonateDispatch
from pythonCah.log import prepareLogging 
from pythonCah.irc.network import WAKEUP_FD_W

import logging
import sys
import traceback
import signal
from glob import glob
from datetime import datetime
logger = logging.getLogger(__name__)

def main():
    prepareLogging(logging.DEBUG)
    logger.info('start app')
    config = loadConfig('config.json')
    BlackCardsFile = glob('./cards/*_q.json')
    WhiteCardsFile = glob('./cards/*_a.json')

    signal.set_wakeup_fd(WAKEUP_FD_W)

    auth = authentication_from_config(config.acl, config.roleMapping)
    dispatch = InpersonateDispatch(BlackCardsFile, WhiteCardsFile, auth)
    bot = CahBot(config, dispatch)
    try:
        bot.start()
    except KeyboardInterrupt:
        print("CTRL + C hit, close the bot")
    except Exception:
        traceback.print_exc(file=sys.stdout)
    sys.exit(0)

if __name__ == "__main__":
    main()
